#pragma once
const int DISPLAY_WIDTH = 1000;
const int DISPLAY_HEIGHT = 600;
const int MENU_WIDTH = 300;
const int MENU_HEIGHT = 350;
const int BUTTON_WIDTH = 200;
const int BUTTON_HEIGHT = 75;
const int PADDLE_WIDTH = 200;
const int PADDLE_HEIGHT = 30;
const double PADDLE_SPEED = 4;
const int BALL_WIDTH = 24;
const int BALL_HEIGHT = 24;
const double BALL_SPEED = 2;
const int NUMBER_WIDTH = 1;		//number of bricks width
const int NUMBER_HEIGHT = 1;		//number of bricks height
const int SCORE_PLUS = 100;
const int SCORE_LIFE_WIDTH = 10;
const int SCORE_LIFE_HEIGHT = 30;
const int HIGHSCORE_WIDTH = 10;
const int HIGHSCORE_HEIGHT = 30;